// Generates src/lib/worldMapPath.ts — a world land silhouette as one SVG path,
// projected with an equirectangular projection fitted to a 1000x500 viewBox.
// Run once (or after changing map size): node scripts/generate-map.mjs
//
// The fitted equirectangular projection is exactly linear, so at runtime
// lon/lat -> x/y is plain arithmetic and no projection library ships to the browser.
import { readFileSync, writeFileSync } from 'node:fs';
import { geoEquirectangular, geoPath } from 'd3-geo';
import { feature } from 'topojson-client';

const WIDTH = 1000;
const HEIGHT = 500;

const topo = JSON.parse(
  readFileSync(new URL('../node_modules/world-atlas/land-110m.json', import.meta.url), 'utf8'),
);
const land = feature(topo, topo.objects.land);

const projection = geoEquirectangular().fitExtent(
  [
    [0, 0],
    [WIDTH, HEIGHT],
  ],
  { type: 'Sphere' },
);

// Sanity check: the fitted projection must match the linear formula the app uses.
const linear = ([lon, lat]) => [((lon + 180) / 360) * WIDTH, ((90 - lat) / 180) * HEIGHT];
for (const probe of [[0, 0], [-180, 90], [180, -90], [127, 37.5]]) {
  const [px, py] = projection(probe);
  const [lx, ly] = linear(probe);
  if (Math.abs(px - lx) > 0.01 || Math.abs(py - ly) > 0.01) {
    throw new Error(`Projection mismatch at ${probe}: ${[px, py]} vs ${[lx, ly]}`);
  }
}

const raw = geoPath(projection)(land);
// One decimal is sub-pixel at render size and halves the file size.
const rounded = raw.replace(/-?\d+\.\d+/g, (m) => Number(m).toFixed(1));

const out = `// Auto-generated by scripts/generate-map.mjs — do not edit by hand.
// World land silhouette (Natural Earth 110m via world-atlas), equirectangular
// projection fitted to a ${WIDTH}x${HEIGHT} viewBox.
export const MAP_WIDTH = ${WIDTH};
export const MAP_HEIGHT = ${HEIGHT};

/** Linear equirectangular mapping matching the generated path. */
export function lonLatToXY(lon: number, lat: number): [number, number] {
  return [((lon + 180) / 360) * MAP_WIDTH, ((90 - lat) / 180) * MAP_HEIGHT];
}

export const LAND_PATH =
  ${JSON.stringify(rounded)};
`;

writeFileSync(new URL('../src/lib/worldMapPath.ts', import.meta.url), out);
console.log(`Wrote src/lib/worldMapPath.ts (${(out.length / 1024).toFixed(0)} KB)`);
